name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: self-hosted
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_shell_escape: true
          continue_on_error: true
        env:
          TEXINPUTS: ".:./custom_template//:"
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: main.pdf
